name: Build Frontend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend  # Chỉ định thư mục chứa package.json

    steps:
      # Bước 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Bước 2: Cài Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # Bước 3: Cài Yarn
      - name: Setup Yarn
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      # Bước 4: Cài dependencies
      - name: Install dependencies
        run: yarn install

      # Bước 5: Build project
      - name: Build frontend
        working-directory: frontend
        run: yarn build

      # Bước 6: Optional: Upload build artifacts
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: frontend/build
